/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-06-28 05:51:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>Login</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom fonts for this template-->\r\n");
      out.write("    <link href=\"resources/vendor/fontawesome-free/css/all.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("    <link\r\n");
      out.write("        href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\"\r\n");
      out.write("        rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom styles for this template-->\r\n");
      out.write("    <link href=\"resources/css/sb-admin-2.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("	");

	
		session = request.getSession();
    	String memberName = (String)session.getAttribute("memberName");
        String memberId = (String)session.getAttribute("memberId");

	
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
 if (memberId == null){ 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"bg-gradient-primary\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Outer Row -->\r\n");
      out.write("        <div class=\"row justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-xl-10 col-lg-12 col-md-9\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card o-hidden border-0 shadow-lg my-5\">\r\n");
      out.write("                    <div class=\"card-body p-0\">\r\n");
      out.write("                        <!-- Nested Row within Card Body -->\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-lg-6 d-none d-lg-block bg-login-image\"></div>\r\n");
      out.write("                            <div class=\"col-lg-6\">\r\n");
      out.write("                                <div class=\"p-5\">\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <h1 class=\"h4 text-gray-900 mb-4\">로그인 화면입니다.</h1>\r\n");
      out.write("                                    </div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("                                    <!-- 로그인 부분 -->\r\n");
      out.write("									<div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control form-control-user\"\r\n");
      out.write("                                                id=\"exampleInputID\" aria-describedby=\"IDHelp\"\r\n");
      out.write("                                                placeholder=\"Enter your ID...\" name = \"id\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input type=\"password\" class=\"form-control form-control-user\"\r\n");
      out.write("                                                id=\"exampleInputPassword\" placeholder=\"Password\" name= \"pw\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"custom-control custom-checkbox small\">\r\n");
      out.write("                                                <input type=\"checkbox\" class=\"custom-control-input\" id=\"customCheck\">\r\n");
      out.write("                                                <label class=\"custom-control-label\" for=\"customCheck\">Remember\r\n");
      out.write("                                                    Me</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        \r\n");
      out.write("                    					<button type=\"button\" class =\"btn btn-primary btn-user btn-block\" onclick = \"login_click();\">로그인</button>\r\n");
      out.write("     \r\n");
      out.write("     									<br>\r\n");
      out.write("                                        <hr>\r\n");
      out.write(" \r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center\">\r\n");
      out.write("                                        <a class=\"small\" href=\"/register\">Create an Account!</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
 } else { 
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("	alert(\"이미 로그인 된 상태입니다.\");\r\n");
      out.write(" 	document.location.href=\"/index\";\r\n");
      out.write(" 	</script>\r\n");
      out.write("\r\n");
  } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("	 <script>\r\n");
      out.write("	 \r\n");
      out.write("	 function login_click(){\r\n");
      out.write("			var userID = $('input[name=\"id\"]').val();\r\n");
      out.write("			var userPW = $('input[name=\"pw\"]').val();\r\n");
      out.write("			var customIDCheck = $('#customCheck').val();\r\n");
      out.write("		     // JSON으로 요청\r\n");
      out.write("			\r\n");
      out.write("		     if(customIDCheck == 'on'){\r\n");
      out.write("		    	 localStorage.setItem(\"saveID\", userID);\r\n");
      out.write("		     }else{\r\n");
      out.write("		    	 localStorage.setItem(\"saveID\", 'N');\r\n");
      out.write("		     }\r\n");
      out.write("		     \r\n");
      out.write("		     \r\n");
      out.write("		     var data = {\"id\" : userID, \"pw\" : userPW};\r\n");
      out.write("		     \r\n");
      out.write("		     $.ajax({\r\n");
      out.write("		\r\n");
      out.write("		              url: \"/login\",\r\n");
      out.write("		\r\n");
      out.write("		              type: \"POST\",\r\n");
      out.write("		\r\n");
      out.write("		              dataType: \"json\",          // ajax 통신으로 받는 타입\r\n");
      out.write("		\r\n");
      out.write("		              contentType: \"application/json\",  // ajax 통신으로 보내는 타입\r\n");
      out.write("		\r\n");
      out.write("		              data: JSON.stringify(data),\r\n");
      out.write("		\r\n");
      out.write("		              success: function(result){\r\n");
      out.write("		            	  \r\n");
      out.write("		            	  if(result.msg == 'FAIL'){\r\n");
      out.write("		            		  alert(\"아이디 또는 비밀번호가 틀렸습니다.\");\r\n");
      out.write("		              	 	window.location.href=\"/login\";\r\n");
      out.write("		\r\n");
      out.write("		            	  }else if(result.msg == 'SUCCESS'){\r\n");
      out.write("		            		alert(result.name + \"님 환영합니다. 로그인 되었습니다.\");\r\n");
      out.write("		            	 	window.location.href=\"/index\";\r\n");
      out.write("		              	  }\r\n");
      out.write("		              },\r\n");
      out.write("				      error: function(result){\r\n");
      out.write("				    	  alert(\"REST 오류 발생\");\r\n");
      out.write("		              	 	window.location.href=\"/\";\r\n");
      out.write("\r\n");
      out.write("				      }\r\n");
      out.write("		\r\n");
      out.write("		     });\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("	\r\n");
      out.write("	 </script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"REGISTERED\"){\r\n");
      out.write("		alert('회원가입 완료 로그인 해주세요');\r\n");
      out.write("		\r\n");
      out.write("	}else if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"UNREGISTERD\"){\r\n");
      out.write("		alert(\"회원가입 오류. 아이디와 비밀번호를 확인해주세요\");\r\n");
      out.write("		window.location.href = \"/register\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core JavaScript-->\r\n");
      out.write("    <script src=\"resources/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"resources/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript-->\r\n");
      out.write("    <script src=\"resources/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages-->\r\n");
      out.write("    <script src=\"resources/js/sb-admin-2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
